version: "3.8"

services:
  backend:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
    command: sh -c "yarn dev && echo 'Backend is running at http://localhost:${SERVER_PORT}'"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    ports:
      - "${REACT_APP_CLIENT_PORT}:${REACT_APP_CLIENT_PORT}"
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    command: sh -c "yarn dev && echo 'Client is running at http://localhost:${REACT_APP_CLIENT_PORT}'"
volumes:
  mongo-data:
