export const propertyTypes = ["Byt", "Dům", "Pozemek"];

export const regions = [
  "Hlavní město Praha",
  "Středočeský kraj",
  "Jihočeský kraj",
  "Plzeňský kraj",
  "Karlovarský kraj",
  "Ústecký kraj",
  "Liberecký kraj",
  "Královéhradecký kraj",
  "Pardubický kraj",
  "Kraj Vysočina",
  "Jihomoravský kraj",
  "Zlínský kraj",
  "Olomoucký kraj",
  "Moravskoslezský kraj",
];

export const districtsByRegion = {
  "Středočeský kraj": [
    "Benešov",
    "Beroun",
    "Kladno",
    "Kolín",
    "Kutná Hora",
    "Mělník",
    "Mladá Boleslav",
    "Nymburk",
    "Praha-východ",
    "Praha-západ",
    "Rakovník",
    "Příbram",
  ],
  "Jihomoravský kraj": [
    "Blansko",
    "Brno-město",
    "Brno-venkov",
    "Břeclav",
    "Český Krumlov",
    "Jindřichův Hradec",
    "Hodonín",
    "Vyškov",
    "Znojmo",
  ],
  "Moravskoslezský kraj": [
    "Bruntál",
    "Frýdek-Místek",
    "Karviná",
    "Nový Jičín",
    "Opava",
    "Ostrava-město",
  ],
  "Liberecký kraj": ["Česká Lípa", "Jablonec nad Nisou", "Liberec", "Semily"],
  "Jihočeský kraj": [
    "České Budějovice",
    "Český Krumlov",
    "Jindřichův Hradec",
    "Hodonín",
    "Pelhřimov",
    "Písek",
    "Strakonice",
  ],
  "Ústecký kraj": [
    "Děčín",
    "Chomutov",
    "Litoměřice",
    "Louny",
    "Most",
    "Teplice",
    "Ústí nad Labem",
    "Ústí nad Orlicí",
  ],
  "Královéhradecký kraj": [
    "Hradec Králové",
    "Jičín",
    "Náchod",
    "Rychnov nad Kněžnou",
    "Trutnov",
  ],
  "Pardubický kraj": ["Chrudim", "Pardubice", "Svitavy", "Ústí nad Orlicí"],
  "Karlovarský kraj": ["Cheb", "Karlovy Vary", "Sokolov"],
  "Zlínský kraj": ["Kroměříž", "Uherské Hradiště", "Vsetín", "Zlín"],
  "Kraj Vysočina": [
    "Havlíčkův Brod",
    "Jihlava",
    "Pelhřimov",
    "Třebíč",
    "Žďár nad Sázavou",
  ],
  "Olomoucký kraj": ["Jeseník", "Olomouc", "Prostějov", "Přerov", "Šumperk"],
  "Plzeňský kraj": [
    "Domažlice",
    "Klatovy",
    "Plzeň-město",
    "Plzeň-jih",
    "Plzeň-sever",
    "Rokycany",
    "Tachov",
  ],
};
